package com.csm.hybrids.client;

import com.csm.hybrids.CsmMod;
import dev.kosmx.playerAnim.api.firstPerson.FirstPersonConfiguration;
import dev.kosmx.playerAnim.api.firstPerson.FirstPersonMode;
import dev.kosmx.playerAnim.api.layered.IAnimation;
import dev.kosmx.playerAnim.api.layered.KeyframeAnimationPlayer;
import dev.kosmx.playerAnim.api.layered.ModifierLayer;
import dev.kosmx.playerAnim.api.layered.modifier.AbstractFadeModifier;
import dev.kosmx.playerAnim.core.data.KeyframeAnimation;
import dev.kosmx.playerAnim.core.util.Ease;
import dev.kosmx.playerAnim.minecraftApi.PlayerAnimationAccess;
import dev.kosmx.playerAnim.minecraftApi.PlayerAnimationFactory;
import dev.kosmx.playerAnim.minecraftApi.PlayerAnimationRegistry;
import net.minecraft.client.player.AbstractClientPlayer;
import net.minecraft.resources.ResourceLocation;

/**
 * PlayerAnimator glue: every player gets a {@link ModifierLayer} on which the hybrid body animations play.
 * Animations live in assets/csm/player_animation/*.json (emotecraft format, generated by tools/player_anims.py).
 */
public final class PlayerAnims {
    public static final ResourceLocation LAYER = CsmMod.id("hybrid");

    public static void init() {
        PlayerAnimationFactory.ANIMATION_DATA_FACTORY.registerFactory(LAYER, 1000, player -> new ModifierLayer<>());
    }

    @SuppressWarnings("unchecked")
    private static ModifierLayer<IAnimation> layer(AbstractClientPlayer player) {
        IAnimation anim = PlayerAnimationAccess.getPlayerAssociatedData(player).get(LAYER);
        return anim instanceof ModifierLayer<?> m ? (ModifierLayer<IAnimation>) m : null;
    }

    public static void play(AbstractClientPlayer player, String name) {
        ModifierLayer<IAnimation> layer = layer(player);
        if (layer == null) {
            return;
        }
        KeyframeAnimation anim = PlayerAnimationRegistry.getAnimation(CsmMod.id(name));
        if (anim == null) {
            CsmMod.LOGGER.warn("Missing player animation csm:{}", name);
            return;
        }
        KeyframeAnimationPlayer player0 = new KeyframeAnimationPlayer(anim)
                .setFirstPersonMode(FirstPersonMode.THIRD_PERSON_MODEL)
                .setFirstPersonConfiguration(new FirstPersonConfiguration(true, true, true, true));
        layer.replaceAnimationWithFade(AbstractFadeModifier.standardFadeIn(3, Ease.INOUTSINE), player0);
    }

    public static void stop(AbstractClientPlayer player) {
        ModifierLayer<IAnimation> layer = layer(player);
        if (layer != null && layer.getAnimation() != null) {
            layer.replaceAnimationWithFade(AbstractFadeModifier.standardFadeIn(4, Ease.INOUTSINE), null);
        }
    }

    private PlayerAnims() {
    }
}
